# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-07 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_teaser', '0003_auto_20160713_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerteaser',
            name='height_units',
            field=models.CharField(choices=[('px', 'pixels (px)'), ('%', 'percent (%)'), ('em', 'relative to font size (em)')], default='px', max_length=2, verbose_name='height units'),
        ),
        migrations.AddField(
            model_name='filerteaser',
            name='width_units',
            field=models.CharField(choices=[('px', 'pixels (px)'), ('%', 'percent (%)'), ('em', 'relative to font size (em)')], default='px', max_length=2, verbose_name='width units'),
        ),
    ]
