# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-07 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
from cmsplugin_filer_video import settings


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_video', '0003_auto_20160713_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='filervideo',
            name='height_units',
            field=models.CharField(choices=[('px', 'pixels (px)'), ('%', 'percent (%)'), ('em', 'relative to font size (em)')], default='px', max_length=2, verbose_name='height units'),
        ),
        migrations.AddField(
            model_name='filervideo',
            name='width_units',
            field=models.CharField(choices=[('px', 'pixels (px)'), ('%', 'percent (%)'), ('em', 'relative to font size (em)')], default='px', max_length=2, verbose_name='width units'),
        ),
        migrations.AddField(
            model_name='filervideo',
            name='controls',
            field=models.BooleanField(default=settings.VIDEO_CONTROLS),
        ),
        migrations.AddField(
            model_name='filervideo',
            name='muted',
            field=models.BooleanField(default=settings.VIDEO_MUTED),
        ),
        migrations.AlterField(
            model_name='filervideo',
            name='movie',
            field=filer.fields.file.FilerFileField(blank=True, help_text='use h264 encoded video file or .webm / .ogg files', null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File', verbose_name='movie file'),
        ),
        migrations.AlterField(
            model_name='filervideo',
            name='movie_url',
            field=models.CharField(blank=True, help_text='vimeo or youtube (embeddable!) video url. Example: https://www.youtube.com/embed/dd4D8tZPfKE', max_length=255, null=True, verbose_name='movie url'),
        ),
        migrations.AddField(
            model_name='filervideo',
            name='preload',
            field=models.CharField(choices=[('auto', 'yes'), ('metadata', 'metadata only'), ('none', 'no')], default='none', max_length=16, verbose_name='preload'),
        ),
    ]
