# Generated by Django 2.2.7 on 2019-11-26 22:31

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_video', '0003_auto_20160713_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filervideo',
            name='auto_hide',
        ),
        migrations.RemoveField(
            model_name='filervideo',
            name='bgcolor',
        ),
        migrations.RemoveField(
            model_name='filervideo',
            name='buttonhighlightcolor',
        ),
        migrations.RemoveField(
            model_name='filervideo',
            name='buttonoutcolor',
        ),
        migrations.RemoveField(
            model_name='filervideo',
            name='buttonovercolor',
        ),
        migrations.RemoveField(
            model_name='filervideo',
            name='fullscreen',
        ),
        migrations.RemoveField(
            model_name='filervideo',
            name='loadingbarcolor',
        ),
        migrations.RemoveField(
            model_name='filervideo',
            name='seekbarbgcolor',
        ),
        migrations.RemoveField(
            model_name='filervideo',
            name='seekbarcolor',
        ),
        migrations.RemoveField(
            model_name='filervideo',
            name='textcolor',
        ),
        migrations.AddField(
            model_name='filervideo',
            name='controls',
            field=models.BooleanField(default=True, verbose_name='controls'),
        ),
        migrations.AddField(
            model_name='filervideo',
            name='height_units',
            field=models.CharField(choices=[('px', 'pixels (px)'), ('%', 'percent (%)'), ('em', 'relative to font size (em)')], default='px', max_length=2, verbose_name='height units'),
        ),
        migrations.AddField(
            model_name='filervideo',
            name='muted',
            field=models.BooleanField(default=False, verbose_name='muted'),
        ),
        migrations.AddField(
            model_name='filervideo',
            name='preload',
            field=models.CharField(choices=[('auto', 'yes'), ('metadata', 'metadata only'), ('none', 'no')], default='none', max_length=16, verbose_name='preload'),
        ),
        migrations.AddField(
            model_name='filervideo',
            name='width_units',
            field=models.CharField(choices=[('px', 'pixels (px)'), ('%', 'percent (%)'), ('em', 'relative to font size (em)')], default='px', max_length=2, verbose_name='width units'),
        ),
        migrations.AlterField(
            model_name='filervideo',
            name='movie',
            field=filer.fields.file.FilerFileField(blank=True, help_text='use h264 encoded video file or .webm / .ogg files', null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File', verbose_name='movie file'),
        ),
        migrations.AlterField(
            model_name='filervideo',
            name='movie_url',
            field=models.CharField(blank=True, help_text='vimeo or youtube (embeddable!) video url. Example: https://www.youtube.com/embed/dd4D8tZPfKE', max_length=255, null=True, verbose_name='movie url'),
        ),
    ]
