# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-07 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
from cmsplugin_filer_video import settings


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_video', '0004_auto_20191107_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name = 'filervideo',
            name = 'bgcolor',
        ),
        migrations.RemoveField(
            model_name = 'filervideo',
            name = 'textcolor',
        ),
        migrations.RemoveField(
            model_name = 'filervideo',
            name = 'seekbarcolor',
        ),
        migrations.RemoveField(
            model_name = 'filervideo',
            name = 'loadingbarcolor',
        ),
        migrations.RemoveField(
            model_name = 'filervideo',
            name = 'buttonoutcolor',
        ),
        migrations.RemoveField(
            model_name = 'filervideo',
            name = 'buttonovercolor',
        ),
        migrations.RemoveField(
            model_name = 'filervideo',
            name = 'buttonhighlightcolor',
        ),
        migrations.RemoveField(
            model_name = 'filervideo',
            name = 'auto_hide',
        ),
        migrations.RemoveField(
            model_name = 'filervideo',
            name = 'seekbarbgcolor',
        ),
        migrations.RemoveField(
            model_name = 'filervideo',
            name = 'fullscreen',
        ),
    ]
